server:
  port: 8080

spring:
  application:
    name: bank-gateway-api

  datasource:
    url: jdbc:mysql://localhost:3306/bank?allowPublicKeyRetrieval=true&sslMode=DISABLED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bitlyuf

  boot:
    admin:
      client:
        url:
          - http://localhost:8001
        username: admin
        password: admin
  cloud:
    gateway:
      default-filters:
        - AuthTokenGlobalFilter
      routes:
        - id: bankApi
          uri: lb://bank-api
          predicates:
            - Path=/bank/**
          filters:
            - StripPrefix=1

        - id: extractApi
          uri: lb://bank-extract-api
          predicates:
            - Path=/extract/**
          filters:
            - StripPrefix=1

        - id: authApi
          uri: lb://bank-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka

jwt:
  config:
    loginUrl: /auth/**
    type: signed
    expiration: 3600
    privateKey: qxBEEQv7E8aviX1KUcdOiF5ve5COUPAr
    header:
      name: Authorization
      prefix: Bearer