server:
  port: 8081
  error:
    include-stacktrace: on_trace_param

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: bank-api

  datasource:
    url: jdbc:mysql://localhost:3306/bank?allowPublicKeyRetrieval=true&sslMode=DISABLED
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: bitlyuf

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    jmx:
      enabled: false

  jackson:
    locale: pt-BR
    time-zone:
      - America/Sao_Paulo

  h2:
    console:
      enabled: true
