server:
  port: ${PORT:9000}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
    register-with-eureka: true

spring:
  application:
    name: bank-auth

  datasource:
    url: jdbc:mysql://localhost:3306/bank?allowPublicKeyRetrieval=true&sslMode=DISABLED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bitlyuf

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false

jwt:
  config:
    loginUrl: /login/**
    type: signed
    expiration: 3600
    privateKey: qxBEEQv7E8aviX1KUcdOiF5ve5COUPAr
    header:
      name: Authorization
      prefix: Bearer

