server:
  port: ${PORT:8082}

spring:
  application:
    name: bank-extract-api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}